# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  healthlextaticoapi:
    environment:
      - IS_DOCKER=True
      - ASPNETCORE_Kestrel__Certificates__Default__Password=lextatico
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Lextatico.pfx
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/https:ro

networks:
  Lextatico:
    external: true
    driver: bridge
